---
title: "HW 1"
output:
  pdf_document: default
  html_notebook: default
  html_document:
    df_print: paged
---
```{r}
library(ggplot2)
```

**Task**: find the area of a figure bounded by curves given by the equation:

$$
 y = 2|x| - \pi, x \in [-{pi\over2},{pi\over2}]
$$
$$
 y = |sin(2x)|, x \in [-{pi\over 2},{pi\over 2}]
$$

using the Monte Carlo method.

You can read about this method in any resource.

For examplle: [www.mathonweb.com/entrtain/monte/t_monte.html](https://www.mathonweb.com/entrtain/monte/t_monte.html)

This is a graphical representation of the equations:
```{r}
x_min <- -pi/2
x_max <- pi/2
y_min <- -3.5
y_max <- 1.5
```

```{r fig.align="center", echo = FALSE,fig.width = 14,fig.height=10}
X <- seq(from=x_min, to=x_max, length.out=100)
Y <- 2*abs(X) - pi
Y <- c(Y, abs(sin(2*X)))
X <- c(X, X)
qplot(X, Y)
```
```{r}
n_points <- 100000
X_mc <- runif(n_points, x_min, x_max)
Y_mc <- runif(n_points, y_min, y_max)
```

```{r}
in_figure <- (Y_mc < abs(sin(2*X_mc))) & (Y_mc > (2*abs(X_mc) - pi))
proportion <- sum(in_figure) / n_points
area <- proportion * (x_max - x_min) * (y_max - y_min)
area
```

```{r}
ggplot() + geom_point(aes(X_mc, Y_mc, colour=in_figure)) + geom_point(aes(X, Y))
```

